### ISSUE TITLE
Drop tax causing incorrect amounts in drop tracker

### ISSUE THREAD

**Issue by HiFiSi** [sobfiggis/Avabur_Enhancer#28]
I was trying to find out if the drop amount for plat shown in the drop tracker were before or after clan taxes were taken out. In trying to find that out, I have discovered a problem with the drop tracker. It's displaying the amount dropped incorrectly for platinum. Possibly for gold as well since that's effected by clan drop tax, however I didn't test that.

So here's what happened. I got the following drop:

You found a pouch containing 103 platinum coins
Your clan took 25 platinum coins as tax

And my total plat increased by 78 (103 minus the 25 for clan drop tax) as it should have

However when I opened the avabur enhancer drop tracker, it said I had received 128 platinum. So it seems like it's adding the drop tax amount to the total drop. In my case, since I was running 25% drop tax, the total plat drop the tracker displayed was 125% of the total amount of plat that dropped. (103 + 25)

The drop tracker should have been showing either 103 platinum (if the drop tracker includes what's taken out for clan drop tax) or 78 (if the drop tracker doesn't include what's taken out for clan drop tax)

This is on the latest version (1.0.9)

EDIT: to verify, I turned off my clan drop tax and the amount shown in the drop tracker was the same amount that I received.

**Comment by sobfiggis** [comment]
Can you confirm the most recent path fixes this?

**Comment by HiFiSi** [comment]
No, the recent update fixed the tracking of multistat/multidrop. It still reports plat drops as the total drop amount + the amount taken for clan tax. For instance, for "You found a box containing 1,317 platinum coins (87 + 1,230 fame-based bonus)! Your clan took 329 platinum coins as tax." the tracker shows a plat drop of 1646 when it should show 1317.

**Comment by kaym0** [comment]
I think this is resolved. Should close @sobfiggis

**Comment by HiFiSi** [comment]
It's not fixed, see screenshot: http://oi66.tinypic.com/2ry6cz4.jpg (taken 5 minutes ago)
The logger should display 129 platinum, not 154.
It's adding the amount of platinum that was taken out for clan tax on top of the full drop amount, so the logger is telling me I got more platinum that was actually dropped.
